### ISSUE TITLE
error when too many requests are made

### ISSUE THREAD

**Issue by algrebe** [deep-compute/funcserver#15]
I get the following error when too many requests are made

```
(funcserver) anto@ant-Dell-n411z:/tmp$ python test.py --log-level debug --port 8888
2016-08-26 13:04:21,325 DEBUG init: args=Namespace(log=None, log_level='debug', name=None, port=8888, quiet=False, statsd_server=None)
2016-08-26 13:04:25,528 INFO 200 GET /rpc/json?fn=hello (127.0.0.1) 3.68ms
2016-08-26 13:04:26,100 INFO 200 GET /rpc/json?fn=hello (127.0.0.1) 2.18ms
2016-08-26 13:04:26,692 INFO 200 GET /rpc/json?fn=hello (127.0.0.1) 2.21ms
2016-08-26 13:04:27,196 INFO 200 GET /rpc/json?fn=hello (127.0.0.1) 2.15ms
2016-08-26 13:04:27,676 INFO 200 GET /rpc/json?fn=hello (127.0.0.1) 2.18ms
2016-08-26 13:04:28,109 INFO 200 GET /rpc/json?fn=hello (127.0.0.1) 2.12ms
2016-08-26 13:04:28,476 INFO 200 GET /rpc/json?fn=hello (127.0.0.1) 2.21ms
2016-08-26 13:04:28,869 INFO 200 GET /rpc/json?fn=hello (127.0.0.1) 3.12ms
2016-08-26 13:04:29,220 INFO 200 GET /rpc/json?fn=hello (127.0.0.1) 2.16ms
2016-08-26 13:04:29,614 INFO 200 GET /rpc/json?fn=hello (127.0.0.1) 2.24ms
2016-08-26 13:04:29,949 INFO 200 GET /rpc/json?fn=hello (127.0.0.1) 2.86ms
2016-08-26 13:04:30,276 INFO 200 GET /rpc/json?fn=hello (127.0.0.1) 2.16ms
2016-08-26 13:04:30,580 INFO 200 GET /rpc/json?fn=hello (127.0.0.1) 2.21ms
2016-08-26 13:04:30,892 INFO 200 GET /rpc/json?fn=hello (127.0.0.1) 2.17ms
Exception in thread Thread-15:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/tmp/funcserver/funcserver/funcserver.py", line 482, in <lambda>
    th = threading.Thread(target=lambda: self._handle_call(self.request, fn, m, protocol))
  File "/tmp/funcserver/funcserver/funcserver.py", line 444, in _handle_call
    self.flush()
  File "/home/anto/.virtualenvs/funcserver/local/lib/python2.7/site-packages/tornado/web.py", line 908, in flush
    start_line, self._headers, chunk, callback=callback)
  File "/home/anto/.virtualenvs/funcserver/local/lib/python2.7/site-packages/tornado/http1connection.py", line 399, in write_headers
    self._pending_write = self.stream.write(data)
  File "/home/anto/.virtualenvs/funcserver/local/lib/python2.7/site-packages/tornado/iostream.py", line 398, in write
    self._handle_write()
  File "/home/anto/.virtualenvs/funcserver/local/lib/python2.7/site-packages/tornado/iostream.py", line 850, in _handle_write
    _merge_prefix(self._write_buffer, num_bytes)
  File "/home/anto/.virtualenvs/funcserver/local/lib/python2.7/site-packages/tornado/iostream.py", line 1528, in _merge_prefix
    if len(deque) == 1 and len(deque[0]) <= size:
TypeError: object of type 'NoneType' has no len()

2016-08-26 13:04:31,477 INFO 200 GET /rpc/json?fn=hello (127.0.0.1) 2.73ms

```
## code

``` python
from gevent import monkey; monkey.patch_all = lambda : None

from funcserver import Server

class TestAPI(object):
    def __init__(self, server):
        self._server = server

    def hello(self):
        return "hello world"

class TestServer(Server):
    def prepare_api(self):
        return TestAPI(self)

    def pre_run(self):
        super(TestServer, self).pre_run()

if __name__ == '__main__':
    TestServer().run()

```
## commands

```
python test.py --log-level debug --port 8888
```

I ran this command serially really fast around 15 times.

```
curl http://localhost:8888/rpc/json?fn=hello
```

**Comment by algrebe** [comment]
this is happening frequently even without any load or concurrent requests

```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/.virtualenvs/peopledb/local/lib/python2.7/site-packages/funcserver/funcserver.py", line 482, in <lambda>
    th = threading.Thread(target=lambda: self._handle_call(self.request, fn, m, protocol))
  File "/root/.virtualenvs/peopledb/local/lib/python2.7/site-packages/funcserver/funcserver.py", line 444, in _handle_call
    self.flush()
  File "/root/.virtualenvs/peopledb/local/lib/python2.7/site-packages/tornado/web.py", line 908, in flush
    start_line, self._headers, chunk, callback=callback)
  File "/root/.virtualenvs/peopledb/local/lib/python2.7/site-packages/tornado/http1connection.py", line 399, in write_headers
    self._pending_write = self.stream.write(data)
  File "/root/.virtualenvs/peopledb/local/lib/python2.7/site-packages/tornado/iostream.py", line 398, in write
    self._handle_write()
  File "/root/.virtualenvs/peopledb/local/lib/python2.7/site-packages/tornado/iostream.py", line 850, in _handle_write
    _merge_prefix(self._write_buffer, num_bytes)
  File "/root/.virtualenvs/peopledb/local/lib/python2.7/site-packages/tornado/iostream.py", line 1528, in _merge_prefix
    if len(deque) == 1 and len(deque[0]) <= size:
TypeError: object of type 'NoneType' has no len()



```
