### ISSUE TITLE
__batch__ works only if it is an attribute of the api

### ISSUE THREAD

**Issue by algrebe** [deep-compute/funcserver#20]
`__batch__` works only if it is a function ( even a dummy function ) of the api, as it is being used to guess mimetype later ( https://github.com/deep-compute/funcserver/blob/master/funcserver/funcserver.py#L433 )

If not present, it throws the following error

```
Exception in thread Thread-5152:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/.virtualenvs/word2vec/local/lib/python2.7/site-packages/funcserver/funcserver.py", line 467, in <lambda>
    th = threading.Thread(target=lambda: self._handle_call(self.request, fn, m, protocol))
  File "/root/.virtualenvs/word2vec/local/lib/python2.7/site-packages/funcserver/funcserver.py", line 433, in _handle_call
    fnobj = self._get_apifn(fn)
  File "/root/.virtualenvs/word2vec/local/lib/python2.7/site-packages/funcserver/funcserver.py", line 357, in _get_apifn
    obj = getattr(obj, part)
AttributeError: 'DVecAPI' object has no attribute '__batch__'
```

**Comment by prashanthellina** [comment]
@algrebe fixed this. please try now.

**Comment by algrebe** [comment]
yes this works.

to serve as documentation 

`cat myserver.py`

``` python
from funcserver import Server

class MyAPI(object):
    def __init__(self):
        pass

    def sum(self, a, b):
        return a + b

class MyServer(Server):
    def prepare_api(self):
        return MyAPI()

if __name__ == '__main__':
    MyServer()
```

``` bash
python myserver.py --port 9345 run
```

`cat data.json`

``` json
{
    "fn": "__batch__",
    "calls": [
        { "fn": "sum", "args": [], "kwargs": { "a": 1, "b": 2 } },
        { "fn": "sum", "args": [], "kwargs": { "a": 4, "b": 2 } },
        { "fn": "sum", "args": [], "kwargs": { "a": 2, "b": 9 } }
    ]
}
```

``` bash
curl -XPOST -d@data.json http://localhost:9345/rpc/json
```
