### ISSUE TITLE
basescript calls target function even before funcserver finishes init

### ISSUE THREAD

**Issue by algrebe** [deep-compute/funcserver#24]
``` python
from funcserver import Server

class TestServer(Server):
    def pre_run(self):
        super(TestServer, self).pre_run()
        print "my stats object is %s" % self.stats

if __name__ == "__main__":
    TestServer()
```

``` bash
(testfuncserver) anto@ant-Dell-n411z:/tmp$ python test.py run
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    TestServer()
  File "/home/anto/.virtualenvs/testfuncserver/local/lib/python2.7/site-packages/funcserver/funcserver.py", line 511, in __init__
    super(Server, self).__init__()
  File "/home/anto/.virtualenvs/testfuncserver/local/lib/python2.7/site-packages/basescript/basescript.py", line 36, in __init__
    self.args.func()
  File "/home/anto/.virtualenvs/testfuncserver/local/lib/python2.7/site-packages/funcserver/funcserver.py", line 695, in run
    self.pre_run()
  File "test.py", line 6, in pre_run
    print "my stats object is %s" % self.stats
AttributeError: 'TestServer' object has no attribute 'stats'
```

The stats object has not been created.
Basescript is calling the `self.args.func` at the end of its `__init__`.
https://github.com/deep-compute/basescript/blob/master/basescript/basescript.py#L36

Funcserver calls basescript's `__init__` 
https://github.com/deep-compute/funcserver/blob/master/funcserver/funcserver.py#L511

Hence, it does not even proceed further to create the stats object at https://github.com/deep-compute/funcserver/blob/master/funcserver/funcserver.py#L513

**Comment by algrebe** [comment]
I've used the following workaround for now

``` python
from funcserver import Server

class TestServer(Server):
    def init(self):
        self.target = self.args.func
        self.args.func = lambda : None

    def pre_run(self):
        super(TestServer, self).pre_run()
        print "my stats object is %s" % self.stats

if __name__ == "__main__":
    t = TestServer()
    t.target()
```

**Comment by prashanthellina** [comment]
@algrebe fixed this and tested with your test script and confirmed it works.
