### ISSUE TITLE
funcserver fails to initialize statsd when subcommand is executed

### ISSUE THREAD

**Issue by algrebe** [deep-compute/funcserver#31]
The statsd server arg namespace is created only for `run`, so when another subcommand is invoked, statsdserver is not part of the argparse namespace.

```python
from funcserver import Server

class Dummy(Server):
    def run(self):
        print "running..."
        print self.args
        super(Dummy, self).run()

    def subcommand_run(self):
        print "subcommand running..."
        print self.args

    def define_args(self, parser):
        super(Dummy, self).define_args(parser)
        parser.add_argument("--runarg", default=None)
        parser.add_argument("--anotherrunarg", default=None)

    def define_subcommands(self, subcommands):
        super(Dummy, self).define_subcommands(subcommands)
        scmd = subcommands.add_parser("subcommand", help="a subcommand")
        scmd.set_defaults(func=self.subcommand_run)
        scmd.add_argument("--scmdarg", default=None)
        scmd.add_argument("--anotherscmdarg", default=None)

if __name__ == '__main__':
    Dummy().start()
```

```
(funcserver) anto@ant-Dell-n411z:/tmp$ python test.py subcommand
Traceback (most recent call last):
  File "test.py", line 26, in <module>
    Dummy().start()
  File "/home/anto/.virtualenvs/funcserver/local/lib/python2.7/site-packages/funcserver/funcserver.py", line 513, in __init__
    self.stats = self.create_stats()
  File "/home/anto/.virtualenvs/funcserver/local/lib/python2.7/site-packages/funcserver/funcserver.py", line 562, in create_stats
    return StatsCollector(stats_prefix, self.args.statsd_server)
AttributeError: 'Namespace' object has no attribute 'statsd_server'
```

**Comment by prashanthellina** [comment]
@algrebe I am not going to resolve this as our plan is to remove StatsD support entirely. When we accomplish that let us close this issue.

**Comment by algrebe** [comment]
#48 and  #44 fix this problem
