### ISSUE TITLE
batch calls are failing

### ISSUE THREAD

**Issue by venugopal-kandru** [deep-compute/funcserver#40]
this commit https://github.com/deep-compute/funcserver/commit/fe8795214cf2b29f4639909a21d8355ae8bfa8e9#diff-222df42061c831dd7027eed6c6aaa036 may be the reason behind this issue.  

Error traceback:
```bash
2017-01-27T13:54:03.811898Z [error    ] Exception during RPC call. fn=__batch__, args='[]', kwargs='{}' _={'ln': 490, 'file': '/usr/local/lib/python2.7/dist-packages/funcserver/funcserver.py', 'name': 'funcserver.funcserver', 'fn': '_handle_call_wrapper'}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/funcserver/funcserver.py", line 485, in _handle_call_wrapper
    return self._handle_call(request, fn, m, protocol)
  File "/usr/local/lib/python2.7/dist-packages/funcserver/funcserver.py", line 439, in _handle_call
    if not r['success']:
TypeError: list indices must be integers, not str
2017-01-27T13:54:03.813229Z [error    ] 500 POST /rpc/json (78.46.20.74) 21.75ms _={'ln': 1971, 'file': '/usr/local/lib/python2.7/dist-packages/tornado/web.py', 'name': 'tornado.access', 'fn': 'log_request'}
```

**Comment by prashanthellina** [comment]
@venugopalkandru Closing this as it has been addressed.
