### ISSUE TITLE
subcommands other than 'run' fail

### ISSUE THREAD

**Issue by algrebe** [deep-compute/funcserver#41]
```
Traceback (most recent call last):
  File "/home/deepcompute/.virtualenvs/crawler/bin/devcrawler", line 11, in <module>
    load_entry_point('crawler==0.0.25', 'console_scripts', 'devcrawler')()
  File "/home/deepcompute/.virtualenvs/crawler/lib/python2.7/site-packages/crawler/devcrawler/devcrawler.py", line 701, in main
    devcrawler = DevCrawler()
  File "/home/deepcompute/.virtualenvs/crawler/lib/python2.7/site-packages/funcserver/funcserver.py", line 563, in __init__
    base_handlers = self.prepare_base_handlers()
  File "/home/deepcompute/.virtualenvs/crawler/lib/python2.7/site-packages/funcserver/funcserver.py", line 675, in prepare_base_handlers
    if self.args.debug:
AttributeError: 'Namespace' object has no attribute 'debug'
```

it is [accessing args.debug](https://github.com/deep-compute/funcserver/blob/d55ba6cac8e858724b9e64edbb5952bd3ff4a241/funcserver/funcserver.py#L577) when the run subcommand isn't active.

Can we modify it such that any tornado specific logic (web ui, websockets etc) should get executed only when the `run` subcommand is invoked.

**Comment by algrebe** [comment]
related to issue #44
