### ISSUE TITLE
funcserver client prints a msgpack exception when calling invalid function

### ISSUE THREAD

**Issue by algrebe** [deep-compute/funcserver#51]
```python
from funcserver import Server

class MyAPI(object):
    def __init__(self): pass

    def add(self, a, b):
        return a + b

class MyServer(Server):
    def prepare_api(self):
        return MyAPI()

if __name__ == '__main__':
    MyServer().start()
```

```
python test.py run --port 8888
```

On the client side, accessing a function that does not exist
```
>>> from funcserver import Client
>>> a = Client('http://localhost:8888')
>>> a.xyz()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anto/github.com/algrebe/funcserver/funcserver/funcserver.py", line 705, in __call__
    return self.parent._call(self.prefix, args, kwargs)
  File "/home/anto/github.com/algrebe/funcserver/funcserver/funcserver.py", line 709, in _call
    return self._do_single_call(fn, args, kwargs)
  File "/home/anto/github.com/algrebe/funcserver/funcserver/funcserver.py", line 730, in _do_single_call
    res = self.DESERIALIZER(req.content)
  File "msgpack/_unpacker.pyx", line 146, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:2231)
msgpack.exceptions.UnpackValueError: Unpack failed: error = 0
```

The logs on the server are accurate. We need to transmit them to client.
```
2017-02-27T15:01:00.972946Z [error    ] RPC failed                     _={'ln': 325, 'file': '/home/anto/github.com/algrebe/funcserver/funcserver/funcserver.py', 'name': 'funcserver.funcserver', 'fn': '_handle_single_call'} args=[] fn='xyz' kwargs={}
Traceback (most recent call last):
  File "/home/anto/github.com/algrebe/funcserver/funcserver/funcserver.py", line 308, in _handle_single_call
    fn = self._get_apifn(fn_name)
  File "/home/anto/github.com/algrebe/funcserver/funcserver/funcserver.py", line 281, in _get_apifn
    obj = getattr(obj, part)
AttributeError: 'MyAPI' object has no attribute 'xyz'
2017-02-27T15:01:00.974387Z [error    ] RPC failed                     _={'ln': 429, 'file': '/home/anto/github.com/algrebe/funcserver/funcserver/funcserver.py', 'name': 'funcserver.funcserver', 'fn': '_handle_call_wrapper'} args=[] fn='xyz' kwargs={}
Traceback (most recent call last):
  File "/home/anto/github.com/algrebe/funcserver/funcserver/funcserver.py", line 426, in _handle_call_wrapper
    return self._handle_call(request, fn, m, protocol)
  File "/home/anto/github.com/algrebe/funcserver/funcserver/funcserver.py", line 351, in _handle_call
    r = self._handle_single_call(request, m)
  File "/home/anto/github.com/algrebe/funcserver/funcserver/funcserver.py", line 344, in _handle_single_call
    fn=fn_name, args=args, kwargs=kwargs,
UnboundLocalError: local variable 'args' referenced before assignment
```

**Comment by prashanthellina** [comment]
Not maintaining funcserver as `kwikapi` is now the preferred option. closing this.
